### ISSUE TITLE
Console.h operating system incompatible key press library

### ISSUE THREAD

**Issue by DaaaPaul** [programming-bros/Tag2D#12]
In `Console.h` there is the `conio.h` library included. 

However, this library is not available on Unix systems. The alternative is `ncurses.h`, but this is not available for Windows systems. 

Require a cross-platform library that does the same job, notably provides functionality that `_kbhit()` and `getch()` does.

**Comment by DaaaPaul** [comment]
Update: there is NO cross-platform library that does this. Will need to define different code for different OS's

**Comment by lexzor** [comment]
To not 'flood' the `Console` system with preprocessor directives for different operating systems, we can create a separate class `ConsoleInput` which should check for input at every frame and emit an event when the user it's sending the input to the application.

It's more code to write to achieve this, at least on Windows.

As far as i read now, the console applications made in Linux are mostly similar. @DaaaPaul could you confirm?

If the above supposition it's correct, we can proceed with Console's Linux compatibility code.

**Comment by DaaaPaul** [comment]
> It's more code to write to achieve this, at least on Windows. As far as i read now, the console applications made in Linux are mostly similar. @DaaaPaul could you confirm?

What do you mean by mostly similar? Like the code or the amount or something else? Its a good suggestion.

**Comment by lexzor** [comment]
Same libraries and, yes, code.

**Comment by DaaaPaul** [comment]
Yes, I can confirm it uses same library and code, I think glfw and OpenGL both have this functionality. Yes, lets do that change

**Comment by lexzor** [comment]
Nice :d. There are more to do on Console system, it s not even finished for Windows. Can you make a PR for this? We can collaborate on it and testing on both operating systems.

**Comment by DaaaPaul** [comment]
Ok, sure!

**Comment by DaaaPaul** [comment]
Wait what do you mean by pull request (sorry im unfamiliar with this), do you mean first I make a new branch then create some change, then request pull?

Because we need changes to pull request right?
