### ISSUE TITLE
Common project isn't being used correctly

### ISSUE THREAD

**Issue by CMDR-JohnAlex** [programming-bros/Tag2D#14]
The Common project is being compiled into a static library, but isn't actually being used. All its .cpp and .h files are being included directly into the builds for Client and Server.

Common was turned into a static library to fix the issue in #3, so we should actually use the static library now to avoid future confusion.

**Comment by lexzor** [comment]
> I feel like changing `kind` to `StaticLib` may be a temporary solution until we come with something better. It's actually not a shared library and the solution it seems superficial.. :(

I merged the branch where the kind has been change as a temporary solution. I consider we should not use the `Common` as a library (even it is static or shared).

I would like for us to find a solution to the current situation, to make it a static library, we should create a new premake group `Utils` which should contain more libraries for each scope (Network, Logger, etc..).
