### ISSUE TITLE
Linking glfw fails on macOS

### ISSUE THREAD

**Issue by DaaaPaul** [programming-bros/Tag2D#9]
<img width="1920" alt="Screenshot 2024-08-07 at 12 31 27 PM" src="https://github.com/user-attachments/assets/ad8527cb-3be3-49d5-8166-8dea424858fc">
<img width="1920" alt="Screenshot 2024-08-07 at 12 31 36 PM" src="https://github.com/user-attachments/assets/b863c2a2-da6a-4e8b-a92a-79a3ed9fbecc">

`ld: symbol(s) not found for architecture arm64`

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

`make[1]: *** [../bin/Debug-macosx-x86_64/Client/Client] Error 1`

`make: *** [Client] Error 2`

**Comment by CMDR-JohnAlex** [comment]
Yeah the premake files need to be modified to add the arm64 architecture, and the glfw premake file that is in the submodule needs to be updated with the files glfw wants compiled for macos. As for what those files are, it may be the same as Linux or we'll have to dig inside glfw's cmake files to check.
The linux build should work though, but I can't test that.

**Comment by lexzor** [comment]
I don't know if it's related to this issue, but `Github Desktop` it's showing this for glfw:

![image](https://github.com/user-attachments/assets/217d4363-dc0c-48fd-a0c2-3c3c04c26d72)

**Comment by DaaaPaul** [comment]
> Yeah the premake files need to be modified to add the arm64 architecture, and the glfw premake file that is in the submodule needs to be updated with the files glfw wants compiled for macos. As for what those files are, it may be the same as Linux or we'll have to dig inside glfw's cmake files to check.

Ok, that makes sense. There are some extra macOS files needed which is not included in Linux such as `IOKit.framework` or `Cocoa.framework`, but im not sure if they are in linking phase or files. Will continue to debug it.

> I don't know if it's related to this issue, but Github Desktop it's showing this for glfw:

Idk, maybe a slight change in Alex's repo? But I don't think it affects much

**Comment by DaaaPaul** [comment]
Update: glfw worked with macOS when I was testing it on my own using the precompiled shared library.

premake5.lua:
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/40aa65d4-55be-4333-845d-c6fefcab2d08">

Directory structure:
<img width="582" alt="image" src="https://github.com/user-attachments/assets/a2864a14-b0c6-4eaf-86cf-09453eac611f">

**Comment by lexzor** [comment]
> Update: glfw worked with macOS when I was testing it on my own using the precompiled shared library.

If there is not any options to make it work without including other precompiled shared libraries, i think we should proceed with pushing this configuration for MacOS.

**Comment by DaaaPaul** [comment]
> If there is not any options to make it work without including other precompiled shared libraries, i think we should proceed with pushing this configuration for MacOS.

Yea we definitley could, lets see what Alex has to say when he is online. The issue is still not fully solved though, because I tested using a blank working directory just with "Hello Window", but the same solution could be implemented into Tag2D.

**Comment by DaaaPaul** [comment]
I will take a break from this issue, I have been debuging it for too long

**Comment by CMDR-JohnAlex** [comment]
> > I don't know if it's related to this issue, but Github Desktop it's showing this for glfw:
> 
> Idk, maybe a slight change in Alex's repo? But I don't think it affects much

Yeah lexzor, you seem to have changed something in the submodule and you haven't pushed those changes to the submodule since that is another repo. What changes does it say you have made? I can either push them to the repo or you can pr changes to [CMDR-JohnAlex/glfw](https://github.com/CMDR-JohnAlex/glfw).

> > If there is not any options to make it work without including other precompiled shared libraries, i think we should proceed with pushing this configuration for MacOS.
> 
> Yea we definitley could, lets see what Alex has to say when he is online. The issue is still not fully solved though, because I tested using a blank working directory just with "Hello Window", but the same solution could be implemented into Tag2D.

Yup, using precompiled glfw for mac is an option and we might as well go for it since mac os seems to be a pain to make work in this way.
I prefer doing the compiling of dependencies ourselves for the reasons I've said on discord before, but if we're spending too much time trying to get it to work then we might as well take this option. 
You've said "_There are some extra macOS files needed which is not included in Linux such as `IOKit.framework` or `Cocoa.framework`_" so I'll try one more thing before you use the precompiled stuff.
